language: cpp
script: make
compiler:
  - gcc
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-4.7 g++-4.7
  - sudo apt-get install -y libjpeg62-dev libglew1.5-dev libflac8 libogg0 libopenal-data libopenal1 libsndfile1 libsoil1 libvorbis0a libvorbisenc2
  - sudo apt-get install -y libgtest-dev
  - wget http://www.sfml-dev.org/files/SFML-2.1-linux-gcc-64bits.tar.bz2
  - tar -xjvf SFML-2.1-linux-gcc-64bits.tar.bz2
  - sudo cp -r SFML-2.1/include/SFML /usr/include/.
  - sudo cp -r SFML-2.1/lib/* /usr/lib/.
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-4.7
  - sudo update-alternatives --auto gcc
  - export CXX=g++-4.7
