language: cpp
script: make
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc
  - sudo apt-get install -y libjpeg62-dev libglew1.5-dev libflac8 libogg0 libopenal-data libopenal1 libsndfile1 libsoil1 libvorbis0a libvorbisenc2
  - wget http://www.sfml-dev.org/files/SFML-2.1-linux-gcc-64bits.tar.bz2
  - tar -xjvf SFML-2.1-linux-gcc-64bits.tar.bz2
  - sudo cp -r SFML-2.1/include/SFML /usr/include/.
  - sudo cp -r SFML-2.1/lib/* /usr/lib/.