#include "EventEnum.hpp"

namespace gs {

const char* EventEnumText[] = {
	"GAME_STATE_CHANGED_EVENT",
	"ENTITY_MOVED_EVENT",
	"ENTITY_CREATED_EVENT",
	"CHANGE_PLAYER_DIRECTION_EVENT",
	"GAME_START_EVENT",
	"GAME_END_EVENT",
	"MENU_ACTION_EVENT",
	"ENTITY_DELETED_EVENT",
	"PLAYER_DESTROYED_EVENT",
	"SCORE_CHANGED_EVENT",
0};

}
